#!/bin/bash

#设置变量

$USER=""
$RSAKEY=""

#创建Ubuntu账户

adduser $USER

#开始导入SSH-key

mkdir /home/$USER/.ssh/

echo "$RSAKEY" >> /home/$USER/.ssh/authorized_keys

#修改ssh配置文件

sed -i "5d" /etc/ssh/sshd_config
sed -i "4a\Port 24180" /etc/ssh/sshd_config

sed -i "29d" /etc/ssh/sshd_config
sed -i "28a\RSAAuthentication yes" /etc/ssh/sshd_config

sed -i "30d" /etc/ssh/sshd_config
sed -i "29a\PubkeyAuthentication yes" /etc/ssh/sshd_config


sed -i "86d" /etc/ssh/sshd_config
sed -i "85a\PermitRootLogin no" /etc/ssh/sshd_config
sed -i "88d" /etc/ssh/sshd_config
sed -i "87a\PasswordAuthentication no" /etc/ssh/sshd_config

service ssh restart

#添加ubuntu账户root权限

chmod u+w /etc/sudoers
rootuser="$USER  ALL=(ALL:ALL) ALL"
sed -i "20a\ $rootuser" /etc/sudoers
chmod u-w /etc/sudoers

#配置项

AddUser_shadowsocks() {
  while :; do echo
    read -p "Please input password for shadowsocks: " Shadowsocks_password
    [ -n "$(echo ${Shadowsocks_password} | grep '[+|&]')" ] && { echo "${CWARNING}input error,not contain a plus sign (+) and & ${CEND}"; continue; }
    (( ${#Shadowsocks_password} >= 5 )) && break || echo "${CWARNING}Shadowsocks password least 5 characters! ${CEND}"
  done
}

Set_ServerIP() {
    read -p "Please input the server IP address: " ServerIPadd
}

Config_shadowsocks(){
mkdir /etc/shadowsocks
cat > /etc/shadowsocks/config.json << EOF
{
    "server":"${ServerIPadd}",
    "local_address":"127.0.0.1",
    "local_port":1080,
    "port_password":{
    "443":"${Shadowsocks_password}"
    },
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open":false
}
EOF
}

Iptables_set() {
iptables -I INPUT -p tcp --dport 443 -j ACCEPT
iptables-save > /etc/iptables.up.rules
}

Set_QRCode() {
url="aes-256-cfd:$Shadowsocks_password@$ServerIPadd:443"
uri=$(echo $url | base64)
qrencode -o SSQRCode.png -s 10 ""ss://"$uri"
echo "Generated new QR Code picture, name QRCode.png. Done"
}

#开始安装Shadowsocks
apt-get install python-pip python-m2crypto -y
pip install shadowsocks
apt-get install qrencode -y
AddUser_shadowsocks
Set_ServerIP
Config_shadowsocks
Iptables_set
Set_QRCode
echo "/usr/bin/python /usr/local/bin/ssserver -c /etc/shadowsocks/config.json -d start" >> /etc/rc.local
ssserver -c /etc/shadowsocks/config.json -d start



