#!/bin/bash 
#这个脚本用来自动生成SS新密码，并使服务生效。最后生成二维码供用户扫描添加配置 
 
#随机生成8位数密码 
pwd=$(pwgen -cs 12 1) 
echo "Generated new ss password: Done" 
 
#组合成SS可以识别的配置文件 
url="aes-256-cfb:$pwd@ss.slivps.xyz:443" 
 
#使用base64对配置文件信息进行加密 
uri=$(echo $url | base64) 
echo "Generated new SS configuration: "ss://"$uri. Done" 
 
#生成二维码 
qrencode -o SSQRCode.png -s 10 ""ss://"$uri" 
echo "Generated new QR Code picture, name QRCode.png. Done"

# 删除原来的容器并开启一个新的docker-shadowsocks容器

docker rm 443port -f
docker run --name 443port --restart always -d -p 443:8388 lishuanglong/alpine-shadowsocks -k $pwd

#发送配置信息邮件给到用户, 请将需要接收邮件的用户邮箱添加到./namelist文件中。 
echo “Now send the configuration info to user...” 
namelist=$(cat ./namelist) #namelist在同一个目录下，如果没有请新建一个 
DATE=$(date +%r/%Y-%m-%d) 
 
echo " 
Hey Guys, 
 
For security reason, we are change the Shadowsocks password every month. Now the newest SS configuration are ready, please reset your Shadowsocks client configuration: 
 
Updated Date: $DATE  
 
Method 1: 
 
Manual imput these info to your SS client. 
 
 * Server Address: ss.slivps.xyz 
 * Server Port: 443 
 * Password: $pwd 
 * Encryption: aes-256-cfb  
 
Method 2: 
 
You also can scan the QR Code to add configuration in attachment.  
 
Method 3: 
 
Copy and paste the below info to the SS-Windows client root gui-config.json file. 
 
    { 
      \"server\": \"ss.slivps.xyz\", 
      \"server_port\": 443, 
      \"password\": \"$pwd\", 
      \"method\": \"aes-256-cfb\", 
      \"remarks\": \"\", 
      \"auth\": false, 
      \"timeout\": 5 
    }, 
 
Thanks 
" > mailbody 
 
mutt -s "Please Reset Your Shadowsocks Configuration Now!" -b $namelist -a ./SSQRCode.png < mailbody 
 
rm -f mailbody 
echo "Done, everything is ready now!" 
 
exit 0
