#!/bin/bash

#设置变量

PASSWORD=""
PORT=""
DOCKERNAME=""
USER=""
RSAKEY=""

#创建Ubuntu账户

adduser $USER

#开始导入SSH-key

mkdir /home/$USER/.ssh/

echo "$RSAKEY" >> /home/$USER/.ssh/authorized_keys

#修改ssh配置文件

sed -i "5d" /etc/ssh/sshd_config
sed -i "4a\Port 24180" /etc/ssh/sshd_config

sed -i "29d" /etc/ssh/sshd_config
sed -i "28a\RSAAuthentication yes" /etc/ssh/sshd_config

sed -i "30d" /etc/ssh/sshd_config
sed -i "29a\PubkeyAuthentication yes" /etc/ssh/sshd_config


sed -i "86d" /etc/ssh/sshd_config
sed -i "85a\PermitRootLogin no" /etc/ssh/sshd_config
sed -i "88d" /etc/ssh/sshd_config
sed -i "87a\PasswordAuthentication no" /etc/ssh/sshd_config

service ssh restart

#添加ubuntu账户root权限

chmod u+w /etc/sudoers
rootuser="$USER  ALL=(ALL:ALL) ALL"
sed -i "20a\ $rootuser" /etc/sudoers
chmod u-w /etc/sudoers

#部署docker

apt-get update
apt-get install docker.io -y
apt-get install qrencode -y
sudo gpasswd -a $USER docker
service docker start
docker run --name $DOCKERNAME --restart always -d -p $PORT:443 lishuanglong/alpine-web -p 443 -k $PASSWORD
su $USER 
